from __future__ import annotations
from src.agent.models import BuySignal, MarketData, SellSignal # SellSignal is not used but included for completeness as per reference

# Rule ID for the signals generated by this module
RULE_ID = "deep_dip_oversold_low_vol_entry_v1"

# Minimum data required for the rule to run
MIN_WARM_CANDLES = 1
MIN_HOT_TICKS = 1

def signal(data: MarketData) -> list[BuySignal | SellSignal]:
    """
    Implements the "Deep Dip Oversold Reversal with Low Volatility Confirmation" trading rule.

    This rule seeks long entry opportunities when the price experiences a significant dip
    below the Keltner Channel (KCP < -20) and is simultaneously oversold (RSI < 35).
    These conditions must be confirmed by sustained low market volatility (BBW < 0.015),
    lower than average trading volume (VDA < 0), and very tight current bid-ask spreads
    (BASP < 0.05), indicating a potential low-risk reversal point in a quiet market.
    """
    signals: list[BuySignal | SellSignal] = []

    for pair, pair_data in data.items():
        # Ensure we have enough data
        if len(pair_data.warm) < MIN_WARM_CANDLES:
            continue
        if len(pair_data.hot) < MIN_HOT_TICKS:
            continue

        latest_warm_candle = pair_data.warm[-1]
        latest_hot_tick = pair_data.hot[-1]

        # Extract indicator values, assuming they are pre-calculated and available
        # on the WarmCandle and Tick objects as per the pseudocode.
        # If these attributes are not present, this will raise an AttributeError,
        # indicating an issue with the data pipeline providing the rule inputs.
        kcp = getattr(latest_warm_candle, 'keltner_channel_percentage', None)
        rsi = getattr(latest_warm_candle, 'rsi', None)
        bbw = getattr(latest_warm_candle, 'bollinger_band_width', None)
        vda = getattr(latest_warm_candle, 'volume_deviation_from_average', None)
        basp = getattr(latest_hot_tick, 'bid_ask_spread_percentage', None)

        # Ensure all required indicators are present (not None) before proceeding
        if any(x is None for x in [kcp, rsi, bbw, vda, basp]):
            # This indicates missing indicator data, which should ideally not happen
            # if the data pipeline is correctly decorating the objects.
            continue

        # Check all conditions for a BUY signal
        condition_kcp = kcp < -20
        condition_rsi = rsi < 35
        condition_bbw = bbw < 0.015
        condition_vda = vda < 0
        condition_basp = basp < 0.05

        if (condition_kcp and
                condition_rsi and
                condition_bbw and
                condition_vda and
                condition_basp):
            signals.append(BuySignal(
                pair=pair,
                timestamp=latest_hot_tick.polled_at,
                price=latest_hot_tick.last_price,
                rule_id=RULE_ID,
                # Optional: Add indicator values for debugging/analysis
                indicators={
                    "kcp": kcp,
                    "rsi": rsi,
                    "bbw": bbw,
                    "vda": vda,
                    "basp": basp,
                }
            ))

    return signals