from __future__ import annotations
import numpy as np
import statistics
from datetime import datetime
from src.agent.models import BuySignal, MarketData, SellSignal, WarmCandle, Tick

# Rule ID for the signals generated by this module
RULE_ID = "fix_rule04_v2"

# Minimum data required for the rule to run
# Max lookback period is 24 for Volume Deviation, so we need at least 24 warm candles.
MIN_WARM_CANDLES = 24
MIN_HOT_TICKS = 1

def _calculate_rsi(closes: np.ndarray, period: int = 14) -> float | None:
    """
    Calculates the Relative Strength Index (RSI) using Simple Moving Averages for gains and losses.
    Requires at least `period + 1` data points.
    """
    if len(closes) < period + 1:
        return None
    
    diffs = np.diff(closes)
    gains = np.maximum(0, diffs)
    losses = np.maximum(0, -diffs)

    # Calculate initial SMAs for gains and losses over the specified period.
    # The 'valid' mode of convolve ensures we have enough data points for each SMA window.
    # We take the last calculated SMA value.
    
    # These arrays will have length len(diffs) - period + 1
    avg_gains = np.convolve(gains, np.ones(period), 'valid') / period
    avg_losses = np.convolve(losses, np.ones(period), 'valid') / period

    if len(avg_gains) == 0 or len(avg_losses) == 0:
        return None

    last_avg_gain = avg_gains[-1]
    last_avg_loss = avg_losses[-1]

    if last_avg_loss == 0:
        # If there are no losses, RSI is 100 if there are gains, otherwise 50 (flat)
        return 100.0 if last_avg_gain > 0 else 50.0 
    
    rs = last_avg_gain / last_avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def _calculate_bollinger_band_width(closes: np.ndarray, period: int = 20) -> float | None:
    """
    Calculates the Bollinger Band Width (BBW).
    BBW = (Upper Band - Lower Band) / Middle Band (SMA)
    Requires at least `period` data points.
    """
    if len(closes) < period:
        return None
    
    # Simple Moving Average (Middle Band)
    sma_series = np.convolve(closes, np.ones(period)/period, mode='valid')
    
    # Rolling Standard Deviation
    # Using a list comprehension for rolling std dev as numpy doesn't have a direct rolling window function for it.
    std_dev_series = np.array([np.std(closes[i-period+1:i+1]) for i in range(period-1, len(closes))])
    
    if len(sma_series) == 0 or len(std_dev_series) == 0:
        return None
    
    last_sma = sma_series[-1]
    last_std_dev = std_dev_series[-1]
    
    # Bollinger Bands are typically SMA +/- 2*STD
    upper_band = last_sma + (2 * last_std_dev)
    lower_band = last_sma - (2 * last_std_dev)
    
    if last_sma == 0:
        return None # Avoid division by zero if SMA is zero
    
    bb_width = (upper_band - lower_band) / last_sma
    return bb_width

def _calculate_keltner_channel_percentage(
    closes: np.ndarray,
    highs: np.ndarray,
    lows: np.ndarray,
    period: int = 20,
    atr_multiplier: float = 2.0
) -> float | None:
    """
    Calculates the Keltner Channel Percentage.
    KCP = ((Close - Mid Line) / (ATR * Multiplier)) * 100
    Requires at least `period` data points for closes, highs, lows, and `period` True Range values.
    """
    if len(closes) < period or len(highs) < period or len(lows) < period:
        return None
    
    # Mid Line: SMA of closes
    mid_line_series = np.convolve(closes, np.ones(period)/period, mode='valid')
    
    # True Range (TR) calculation
    # TR values start from the second candle (index 1) as they need the previous close.
    # TR = max(H-L, abs(H-C_prev), abs(L-C_prev))
    tr_values = []
    for i in range(1, len(closes)):
        tr_values.append(
            max(highs[i] - lows[i], abs(highs[i] - closes[i-1]), abs(lows[i] - closes[i-1]))
        )
    
    if not tr_values or len(tr_values) < period:
        return None
    
    tr_values = np.array(tr_values)
    
    # Average True Range (ATR): SMA of TR
    # The ATR series will be aligned with the end of the `tr_values` array.
    atr_series = np.convolve(tr_values, np.ones(period)/period, mode='valid')
    
    if len(mid_line_series) == 0 or len(atr_series) == 0:
        return None

    # Take the last calculated values for the current candle
    last_mid_line = mid_line_series[-1]
    last_atr = atr_series[-1]
    
    if last_atr == 0:
        return None # Avoid division by zero if ATR is zero
    
    kcp = ((closes[-1] - last_mid_line) / (last_atr * atr_multiplier)) * 100
    return kcp

def _calculate_volume_deviation(volumes: np.ndarray, period: int = 24) -> float | None:
    """
    Calculates the percentage deviation of the latest volume from the average of the
    previous `period-1` volumes.
    Requires at least `period` data points.
    """
    if len(volumes) < period:
        return None

    # Calculate average volume of the `period-1` preceding candles
    # volumes[-(period):-1] slices the array from the `period`-th element from the end
    # up to (but not including) the last element.
    avg_volume_history = np.mean(volumes[-(period):-1])
    latest_volume = volumes[-1]
    
    if avg_volume_history == 0:
        # If historical average volume is zero, deviation is undefined.
        # Return 0 if latest volume is also zero, otherwise a large positive number.
        return 0.0 if latest_volume == 0 else 1000.0
    
    volume_deviation = ((latest_volume - avg_volume_history) / avg_volume_history) * 100
    return volume_deviation

def signal(data: MarketData) -> list[BuySignal | SellSignal]:
    """
    Implements the "Refined Low Volatility Keltner Dip/Recovery with Volume Confirmation" trading rule.

    This rule triggers a BUY signal when:
    - Hourly Bollinger Band Width is below 0.03 (low volatility).
    - Hourly RSI is between 34 and 48 (oversold/recovering from oversold).
    - Hourly Keltner Channel Percentage is between -50 and 60 (capturing dips and early recoveries).
    - Tick Bid-Ask Spread Percentage is below 0.10 (tight spreads, low transaction cost).
    - Hourly Volume Deviation from Average is above 15% (strong volume conviction).
    """
    signals: list[BuySignal | SellSignal] = []

    for pair, pair_data in data.items():
        # Ensure we have enough data for all indicators
        if len(pair_data.warm) < MIN_WARM_CANDLES:
            continue
        if len(pair_data.hot) < MIN_HOT_TICKS:
            continue

        latest_warm_candle = pair_data.warm[-1]
        latest_hot_tick = pair_data.hot[-1]

        # Prepare numpy arrays for indicator calculations
        closes = np.array([c.close for c in pair_data.warm])
        highs = np.array([c.high for c in pair_data.warm])
        lows = np.array([c.low for c in pair_data.warm])
        volumes = np.array([c.volume for c in pair_data.warm])

        # Calculate all required indicators
        rsi_val = _calculate_rsi(closes, period=14)
        bb_width_val = _calculate_bollinger_band_width(closes, period=20)
        keltner_pct_val = _calculate_keltner_channel_percentage(closes, highs, lows, period=20)
        volume_deviation_val = _calculate_volume_deviation(volumes, period=24)

        # Calculate Bid-Ask Spread Percentage from the latest tick
        bid_ask_spread_pct = None
        if latest_hot_tick.last_price > 0: # Ensure last_price is not zero to avoid division by zero
            bid_ask_spread_pct = (latest_hot_tick.ask_price - latest_hot_tick.bid_price) / latest_hot_tick.last_price * 100

        # Ensure all required indicators were calculated successfully (not None)
        if any(x is None for x in [rsi_val, bb_width_val, keltner_pct_val, volume_deviation_val, bid_ask_spread_pct]):
            continue

        # Apply the conditions for a BUY signal
        condition_rsi = 34 <= rsi_val <= 48
        condition_bb_width = bb_width_val < 0.03
        condition_keltner_pct = -50 <= keltner_pct_val <= 60
        condition_bid_ask_spread = bid_ask_spread_pct < 0.10
        condition_volume_deviation = volume_deviation_val > 15 # Percentage

        if (condition_rsi and
            condition_bb_width and
            condition_keltner_pct and
            condition_bid_ask_spread and
            condition_volume_deviation):
            
            entry_price = latest_hot_tick.last_price
            
            # The BuySignal model does not support take_profit_target or stop_loss_limit directly
            # These are typically handled by the agent that processes the signal.
            # However, if they were to be included, they would be calculated here:
            # take_profit_target = entry_price * 1.02
            # stop_loss_limit = entry_price * 0.98

            signals.append(BuySignal(
                pair=pair,
                timestamp=latest_hot_tick.polled_at,
                price=entry_price,
                rule_id=RULE_ID,
                indicators={
                    "rsi": rsi_val,
                    "bb_width": bb_width_val,
                    "keltner_pct": keltner_pct_val,
                    "volume_dev": volume_deviation_val,
                    "bid_ask_spread_pct": bid_ask_spread_pct,
                }
            ))

    return signals