from __future__ import annotations
import statistics
import numpy as np
from src.agent.models import BuySignal, SellSignal, PairData, Tick

# --- Rule Configuration ---
RULE_ID = "rule_12_lead_lag_v3"

# Default parameters for the rule logic
LAG_PERIOD = 5  # Period over which to calculate leading asset's price change
LOOKBACK_PERIOD_VOL = 10  # Lookback period for leading asset's volatility
LOOKBACK_PERIOD_TREND = 3  # Lookback period for lagging asset's trend (ROC)
VOLATILITY_MULTIPLIER = 1.5  # Multiplier for volatility to determine the threshold
TREND_THRESHOLD = 0.001  # Minimum percentage change for lagging asset's trend confirmation (e.g., 0.1%)

# Minimum number of ticks required for all calculations.
# This ensures enough data for:
# - leading_returns: LAG_PERIOD + 1 ticks (current price + price from LAG_PERIOD ago)
# - leading_volatility: LOOKBACK_PERIOD_VOL + 1 ticks (to calculate LOOKBACK_PERIOD_VOL returns)
# - lagging_asset_roc: LOOKBACK_PERIOD_TREND + 1 ticks
MIN_TICKS = max(LAG_PERIOD + 1, LOOKBACK_PERIOD_VOL + 1, LOOKBACK_PERIOD_TREND + 1)

# --- Crucial Assumption for Leading Asset Identification ---
# This rule requires a leading asset whose price movements are used to predict the lagging asset.
# We assume the leading asset is identified by a specific key in the MarketData.
# For example, if we are trading ETH/USD (lagging), BTC/USD (leading) might be used.
# This makes the rule less generic; a more robust solution would involve a configuration mapping
# (e.g., {"ETH/USD": "BTC/USD"}). For this implementation, we hardcode an example.
LEADING_ASSET_KEY = "BTC/USD"  # Example: Assuming BTC/USD is the leading asset.

MarketData = dict[str, PairData]

# --- Helper Functions ---

def _get_prices(ticks: list[Tick]) -> np.ndarray:
    """Extracts last_price from a list of Tick objects."""
    if not ticks:
        return np.array([])
    return np.array([t.last_price for t in ticks])

def _calculate_volatility(prices: np.ndarray, lookback: int) -> float:
    """
    Calculates the standard deviation of *returns* (volatility) over a lookback period.
    This provides a percentage-based volatility measure, consistent with leading_returns.
    """
    if len(prices) <= lookback:
        return 0.0

    # We need (lookback + 1) prices to calculate 'lookback' number of returns.
    # Example: for lookback=10, we need prices[P_t-10, ..., P_t-1, P_t]
    relevant_prices = prices[-(lookback + 1):]

    # Avoid division by zero for past prices
    if np.any(relevant_prices[:-1] == 0):
        return 0.0

    # Calculate percentage returns: (P_current / P_previous) - 1
    returns = (relevant_prices[1:] / relevant_prices[:-1]) - 1

    if len(returns) == 0:
        return 0.0

    return np.std(returns)

def _calculate_roc(prices: np.ndarray, lookback: int) -> float:
    """Calculates the Rate of Change (ROC) for prices over a lookback period."""
    if len(prices) <= lookback:  # Need at least (lookback + 1) prices for ROC
        return 0.0
    current_price = prices[-1]
    past_price = prices[-1 - lookback]
    if past_price == 0:  # Avoid division by zero
        return 0.0
    return (current_price - past_price) / past_price

def lead_lag_v3(data: MarketData) -> list[BuySignal | SellSignal]:
    """
    Implements a Lead-Lag trading rule with volatility-adjusted thresholds and trend confirmation.

    A buy signal for the lagging asset is emitted if:
    1. The leading asset's price change (over lag_period) exceeds a threshold
       proportional to its recent volatility.
    2. The lagging asset's short-term price trend (ROC) is positive and above a trend_threshold.

    A sell signal for the lagging asset is emitted if:
    1. The leading asset's price change (over lag_period) falls below a negative
       volatility-adjusted threshold.
    2. The lagging asset's short-term price trend (ROC) is negative and below a -trend_threshold.

    Args:
        data: A dictionary of MarketData, where keys are pair IDs (e.g., "BTC/USD")
              and values are PairData objects containing historical tick data.

    Returns:
        A list of BuySignal or SellSignal objects generated by the rule.
    """
    signals: list[BuySignal | SellSignal] = []

    # 1. Retrieve leading asset data
    if LEADING_ASSET_KEY not in data:
        return [] # Leading asset data not available

    leading_asset_pair_data = data[LEADING_ASSET_KEY]
    leading_asset_ticks = leading_asset_pair_data.hot
    leading_asset_prices = _get_prices(leading_asset_ticks)

    # Ensure sufficient data for the leading asset for all lookback periods
    if len(leading_asset_prices) < MIN_TICKS:
        return []

    # 2. Iterate through all other pairs, treating them as lagging assets
    for pair, pair_data in data.items():
        if pair == LEADING_ASSET_KEY:
            continue  # Skip the leading asset itself; we're looking for lagging pairs

        lagging_asset_ticks = pair_data.hot
        lagging_asset_prices = _get_prices(lagging_asset_ticks)

        # Ensure sufficient data for the lagging asset for all lookback periods
        if len(lagging_asset_prices) < MIN_TICKS:
            continue

        # --- Rule Logic Application ---

        # Calculate returns for leading asset over lag_period
        # Requires at least (LAG_PERIOD + 1) prices
        leading_current_price = leading_asset_prices[-1]
        leading_past_price = leading_asset_prices[-1 - LAG_PERIOD]
        if leading_past_price == 0:
            continue # Avoid division by zero
        leading_returns = (leading_current_price - leading_past_price) / leading_past_price

        # Calculate recent volatility for leading asset (std dev of returns)
        # Requires at least (LOOKBACK_PERIOD_VOL + 1) prices
        leading_volatility = _calculate_volatility(leading_asset_prices, LOOKBACK_PERIOD_VOL)

        # If volatility is zero, it implies no significant movement or data issues.
        # This would lead to zero thresholds, making even tiny returns trigger signals,
        # which is usually not desired for a "volatility-adjusted" rule.
        if leading_volatility == 0:
            continue

        # Calculate volatility-adjusted thresholds
        buy_threshold = VOLATILITY_MULTIPLIER * leading_volatility
        sell_threshold = -VOLATILITY_MULTIPLIER * leading_volatility

        # Calculate short-term trend for lagging asset (Rate of Change)
        # Requires at least (LOOKBACK_PERIOD_TREND + 1) prices
        lagging_asset_roc = _calculate_roc(lagging_asset_prices, LOOKBACK_PERIOD_TREND)

        # Get current data for signal generation
        current_timestamp = lagging_asset_ticks[-1].polled_at
        current_price = lagging_asset_ticks[-1].last_price

        # Generate signals based on combined conditions
        if leading_returns > buy_threshold and lagging_asset_roc > TREND_THRESHOLD:
            signals.append(BuySignal(
                pair=pair,
                rule_id=RULE_ID,
                timestamp=current_timestamp,
                price=current_price,
            ))
        elif leading_returns < sell_threshold and lagging_asset_roc < -TREND_THRESHOLD:
            signals.append(SellSignal(
                pair=pair,
                rule_id=RULE_ID,
                timestamp=current_timestamp,
                price=current_price,
            ))

    return signals