from __future__ import annotations

import numpy as np
from datetime import datetime

from src.agent.models import BuySignal, MarketData, SellSignal

# --- Rule Parameters ---
# The period for calculating the Simple Moving Average (SMA) and Standard Deviation (STDDEV).
PERIOD = 20

# The standard deviation multiplier for the Bollinger Bands.
# This is the key adjustment: reduced from 2.2 to 2.0 for narrower bands,
# aiming to increase signal frequency.
STD_DEV_MULTIPLIER = 2.0


def signal(data: MarketData) -> list[BuySignal | SellSignal]:
    """
    Implements the Bollinger Band v3 Multiplier Adjustment trading rule.

    This rule modifies rule_02_bollinger_band_v3 by adjusting the Bollinger Band
    standard deviation multiplier from 2.2 to 2.0. The aim is to increase the
    frequency of signals generated by the high-potential Bollinger Band v3 rule,
    which previously had a very low signal count, while maintaining its strong
    mean-reversion characteristics.

    It emits a buy signal if the current price drops below the lower band
    (2.0 std dev) and a sell signal if it rises above the upper band (2.0 std dev).

    Args:
        data: A MarketData object containing tick and candle data for various
              currency pairs.

    Returns:
        A list of BuySignal or SellSignal objects indicating trading opportunities.
    """
    signals: list[BuySignal | SellSignal] = []

    for pair, pair_data in data.items():
        # Ensure we have enough warm candle data to calculate Bollinger Bands for the specified period.
        if len(pair_data.warm) < PERIOD:
            continue

        # Extract closing prices for the last 'PERIOD' candles.
        closes = np.array([c.close for c in pair_data.warm[-PERIOD:]])

        # Calculate the Middle Band (MB) as the Simple Moving Average (SMA) of closes.
        middle_band = np.mean(closes)

        # Calculate the Standard Deviation (STDDEV) of closes.
        # np.std calculates the population standard deviation by default, which is
        # standard practice for Bollinger Bands.
        std_dev = np.std(closes)

        # If standard deviation is zero, all prices in the window are identical.
        # This makes the bands collapse, rendering signals meaningless. Skip such cases.
        if std_dev == 0:
            continue

        # Calculate the Upper Band (UB) and Lower Band (LB) using the adjusted multiplier.
        upper_band = middle_band + (STD_DEV_MULTIPLIER * std_dev)
        lower_band = middle_band - (STD_DEV_MULTIPLIER * std_dev)

        # Ensure there is hot (tick) data to get the current price for comparison.
        if not pair_data.hot:
            continue

        # Get the current price and timestamp from the most recent tick.
        current_tick = pair_data.hot[-1]
        current_price = current_tick.last_price
        timestamp = current_tick.polled_at

        # Generate buy or sell signals based on price crossing the bands.
        # Buy Signal: Current price falls below the lower band (oversold).
        if current_price < lower_band:
            signals.append(BuySignal(pair=pair, timestamp=timestamp, price=current_price))
        # Sell Signal: Current price rises above the upper band (overbought).
        elif current_price > upper_band:
            signals.append(SellSignal(pair=pair, timestamp=timestamp, price=current_price))

    return signals