from __future__ import annotations
import statistics
from datetime import datetime
from src.agent.models import BuySignal, MarketData, SellSignal, WarmCandle

# Parameters
VWAP_PERIOD = 20  # Lookback period for VWAP and standard deviation (in bars/candles)
BAND_MULTIPLIER = 1.5  # Multiplier for standard deviation to define upper and lower bands
RULE_ID = "5e3fc848-8f01-41bf-839a-2952182aaeb2"

def signal(data: MarketData) -> list[BuySignal | SellSignal]:
    """
    Implements the VWAP Bands Trading Rule.

    This rule identifies potential overbought or oversold conditions by comparing the
    current price to a Volume-Weighted Average Price (VWAP) and its dynamic bands.
    A Buy signal is generated when the current price falls below the lower VWAP band,
    suggesting the asset is undervalued. A Sell signal is triggered when the price
    rises above the upper VWAP band, indicating potential overvaluation.
    The bands are calculated using a multiple of the standard deviation of price
    over the VWAP period, providing adaptability to changing volatility.

    Args:
        data: A MarketData object containing tick, warm (hourly candles), and cold data.

    Returns:
        A list of BuySignal or SellSignal objects generated by the rule.
    """
    signals: list[BuySignal | SellSignal] = []

    for pair, pair_data in data.items():
        warm_candles: list[WarmCandle] = pair_data.warm

        # Ensure we have enough data points for the VWAP period
        if len(warm_candles) < VWAP_PERIOD:
            continue

        # Get the most recent VWAP_PERIOD candles
        relevant_candles = warm_candles[-VWAP_PERIOD:]
        current_candle = warm_candles[-1]

        typical_prices: list[float] = []
        vwap_numerator: float = 0.0
        vwap_denominator: float = 0.0

        for candle in relevant_candles:
            # Calculate Typical Price for each candle
            typical_price = (candle.high + candle.low + candle.close) / 3
            typical_prices.append(typical_price)

            # Accumulate for VWAP calculation
            vwap_numerator += typical_price * candle.volume
            vwap_denominator += candle.volume

        # Handle cases with zero total volume to prevent division by zero
        if vwap_denominator == 0:
            continue

        # Calculate VWAP
        vwap = vwap_numerator / vwap_denominator

        # Calculate Standard Deviation of Typical Price over the period
        # statistics.stdev requires at least 2 data points.
        if len(typical_prices) < 2:
            continue
        try:
            std_dev = statistics.stdev(typical_prices)
        except statistics.StatisticsError:
            # This can happen if all typical_prices are identical
            # In such a case, std_dev is 0, and bands collapse to VWAP.
            # We can treat this as 0 and proceed, or skip. For now, let's treat as 0.
            std_dev = 0.0

        # Calculate Upper and Lower Bands
        upper_band = vwap + (std_dev * BAND_MULTIPLIER)
        lower_band = vwap - (std_dev * BAND_MULTIPLIER)

        # Get current Close Price for signal generation
        current_price = current_candle.close
        timestamp = current_candle.hour

        # Generate Signals
        if current_price < lower_band:
            signals.append(BuySignal(
                pair=pair,
                timestamp=timestamp,
                price=current_price,
                rule_id=RULE_ID
            ))
        elif current_price > upper_band:
            signals.append(SellSignal(
                pair=pair,
                timestamp=timestamp,
                price=current_price,
                rule_id=RULE_ID
            ))

    return signals