from __future__ import annotations
import statistics
from datetime import datetime
from src.agent.models import BuySignal, MarketData, SellSignal, WarmCandle

# Parameters
VWAP_PERIOD = 20  # Lookback period for VWAP and standard deviation (in bars/candles)
# The description aims for "tighter bands" by "slightly reducing the standard deviation multiplier".
# The original rule_15_vwap_bands_trading_rule_v1 used a multiplier of 1.5.
# To achieve tighter bands (reduction from 1.5), we'll set it to 1.2.
# The pseudocode's 1.8 would make bands wider, contradicting the stated goal.
BAND_MULTIPLIER = 1.2
# Use the idea_id as the rule_id for this specific modification.
RULE_ID = "43a87572-e363-462e-9e43-e685be54a1ce"

def signal(data: MarketData) -> list[BuySignal | SellSignal]:
    """
    Implements the VWAP Bands Optimization: Tighter Standard Deviation Multiplier rule.

    This rule is a modification of rule_15_vwap_bands_trading_rule_v1. It aims to improve
    signal timeliness and profitability by reducing the standard deviation multiplier
    used for calculating the upper and lower VWAP bands. The goal is to make the bands tighter,
    allowing for earlier detection of price deviations from VWAP, and potentially capturing
    mean-reversion movements more effectively.

    A Buy signal is generated when the current price falls below the lower VWAP band,
    suggesting the asset is undervalued. A Sell signal is triggered when the price
    rises above the upper VWAP band, indicating potential overvaluation.
    The bands are calculated using a multiple of the standard deviation of price
    over the VWAP period, providing adaptability to changing volatility.

    Args:
        data: A MarketData object containing tick, warm (hourly candles), and cold data.

    Returns:
        A list of BuySignal or SellSignal objects generated by the rule.
    """
    signals: list[BuySignal | SellSignal] = []

    for pair, pair_data in data.items():
        warm_candles: list[WarmCandle] = pair_data.warm

        # Ensure we have enough data points for the VWAP period
        if len(warm_candles) < VWAP_PERIOD:
            continue

        # Get the most recent VWAP_PERIOD candles
        relevant_candles = warm_candles[-VWAP_PERIOD:]
        current_candle = warm_candles[-1]

        typical_prices: list[float] = []
        vwap_numerator: float = 0.0
        vwap_denominator: float = 0.0

        for candle in relevant_candles:
            # Calculate Typical Price for each candle
            typical_price = (candle.high + candle.low + candle.close) / 3
            typical_prices.append(typical_price)

            # Accumulate for VWAP calculation
            vwap_numerator += typical_price * candle.volume
            vwap_denominator += candle.volume

        # Handle cases with zero total volume to prevent division by zero
        if vwap_denominator == 0:
            continue

        # Calculate VWAP
        vwap = vwap_numerator / vwap_denominator

        # Calculate Standard Deviation of Typical Price over the period
        # statistics.stdev requires at least 2 data points.
        if len(typical_prices) < 2:
            # If there's only one data point, standard deviation is undefined or 0.
            # In a period of 20, this should ideally not be hit unless data is malformed.
            std_dev = 0.0
        else:
            try:
                std_dev = statistics.stdev(typical_prices)
            except statistics.StatisticsError:
                # This can happen if all typical_prices are identical, resulting in zero std_dev.
                std_dev = 0.0

        # Calculate Upper and Lower Bands with the modified multiplier
        upper_band = vwap + (std_dev * BAND_MULTIPLIER)
        lower_band = vwap - (std_dev * BAND_MULTIPLIER)

        # Get current Close Price for signal generation
        current_price = current_candle.close
        timestamp = current_candle.hour

        # Generate Signals
        if current_price < lower_band:
            signals.append(BuySignal(
                pair=pair,
                timestamp=timestamp,
                price=current_price,
                rule_id=RULE_ID
            ))
        elif current_price > upper_band:
            signals.append(SellSignal(
                pair=pair,
                timestamp=timestamp,
                price=current_price,
                rule_id=RULE_ID
            ))

    return signals