from __future__ import annotations
import statistics
from datetime import datetime
from src.agent.models import BuySignal, MarketData, SellSignal, WarmCandle

# Parameters
VWAP_PERIOD = 20  # Period for VWAP calculation and standard deviation of typical price
BAND_MULTIPLIER = 2.0  # Standard deviation multiplier for VWAP bands
VOLUME_MA_PERIOD = 10  # Period for moving average of volume
VOLUME_SPIKE_MULTIPLIER = 1.5  # Multiplier for volume spike confirmation
RULE_ID = "1453cfaa-7ffd-40ca-8333-87cb425b436b" # Unique ID for this rule

def signal(data: MarketData) -> list[BuySignal | SellSignal]:
    """
    Implements the VWAP Bands with Volume Confirmation Trading Rule.

    This rule enhances the existing VWAP Bands strategy by adding a volume confirmation.
    A Buy signal is generated only when the price falls below the lower VWAP band AND
    the trading volume is significantly higher than its recent average, indicating
    strong conviction behind the price deviation. Conversely, a Sell signal requires
    the price to rise above the upper VWAP band AND be accompanied by high volume.
    This aims to filter out weak signals and identify high-conviction mean-reversion opportunities.

    Args:
        data: A MarketData object containing tick, warm (hourly candles), and cold data.

    Returns:
        A list of BuySignal or SellSignal objects generated by the rule.
    """
    signals: list[BuySignal | SellSignal] = []

    # Determine the minimum number of candles required for all calculations
    # We need VWAP_PERIOD for VWAP/bands and VOLUME_MA_PERIOD for average volume.
    # Both sets of calculations must end at the current candle.
    min_candles_required = max(VWAP_PERIOD, VOLUME_MA_PERIOD)

    for pair, pair_data in data.items():
        warm_candles: list[WarmCandle] = pair_data.warm

        # Ensure we have enough data points for both VWAP and Volume MA calculations
        if len(warm_candles) < min_candles_required:
            continue

        current_candle = warm_candles[-1]
        timestamp = current_candle.hour
        current_price = current_candle.close
        current_volume = current_candle.volume

        # --- 1. Calculate VWAP and Bands ---
        # Get candles relevant for VWAP and StdDev calculation (last VWAP_PERIOD candles)
        vwap_relevant_candles = warm_candles[-VWAP_PERIOD:]

        typical_prices: list[float] = []
        vwap_numerator: float = 0.0
        vwap_denominator: float = 0.0

        for candle in vwap_relevant_candles:
            # Calculate Typical Price for each candle
            typical_price = (candle.high + candle.low + candle.close) / 3
            typical_prices.append(typical_price)

            # Accumulate for VWAP calculation
            vwap_numerator += typical_price * candle.volume
            vwap_denominator += candle.volume

        # Handle cases with zero total volume to prevent division by zero
        if vwap_denominator == 0:
            continue

        # Calculate VWAP
        vwap = vwap_numerator / vwap_denominator

        # Calculate Standard Deviation of Typical Price over the period
        # statistics.stdev requires at least 2 data points.
        if len(typical_prices) < 2:
            # If not enough data points for std dev, we can't form bands.
            continue
        try:
            std_dev = statistics.stdev(typical_prices)
        except statistics.StatisticsError:
            # This can happen if all typical_prices are identical, meaning std_dev is 0.
            # In this case, bands would collapse to VWAP, which is a valid (though perhaps
            # not useful) state. Let's explicitly set it to 0.0.
            std_dev = 0.0

        # Calculate Upper and Lower Bands
        upper_band = vwap + (std_dev * BAND_MULTIPLIER)
        lower_band = vwap - (std_dev * BAND_MULTIPLIER)

        # --- 2. Calculate Average Volume and Check for Spike ---
        # Get candles relevant for Volume MA (last VOLUME_MA_PERIOD candles)
        volume_relevant_candles = warm_candles[-VOLUME_MA_PERIOD:]

        if len(volume_relevant_candles) < VOLUME_MA_PERIOD:
            # This check is technically redundant if min_candles_required is max(VWAP_PERIOD, VOLUME_MA_PERIOD)
            # and VWAP_PERIOD is not smaller than VOLUME_MA_PERIOD, but good for robustness.
            continue

        # Extract volumes for MA calculation
        volumes = [candle.volume for candle in volume_relevant_candles]

        # Handle cases where all volumes are zero or not enough data for mean
        if not volumes or sum(volumes) == 0:
            # Cannot determine average volume or spike without historical volume
            continue

        avg_volume = statistics.mean(volumes)

        # Check for volume spike
        is_volume_spike = current_volume > (avg_volume * VOLUME_SPIKE_MULTIPLIER)

        # --- 3. Generate Signals with Volume Confirmation ---
        if is_volume_spike:
            if current_price < lower_band:
                signals.append(BuySignal(
                    pair=pair,
                    timestamp=timestamp,
                    price=current_price,
                    rule_id=RULE_ID
                ))
            elif current_price > upper_band:
                signals.append(SellSignal(
                    pair=pair,
                    timestamp=timestamp,
                    price=current_price,
                    rule_id=RULE_ID
                ))

    return signals